# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Fax-Machine' do


inhibit_all_warnings!

 pod 'Parse'
 pod 'ParseUI'
 pod 'ParseTwitterUtils'
 pod 'FBSDKCoreKit'
 pod 'FBSDKLoginKit'
 pod 'ParseFacebookUtilsV4'
 pod 'RESideMenu'
 pod 'FontAwesomeKit'
 pod 'FCCurrentLocationGeocoder'
 pod 'MBProgressHUD'
 pod 'YYWebImage'
 pod 'SCLAlertView-Objective-C'
 pod 'PullToRefreshCoreText'
 pod 'AWSCore'
 pod 'AWSS3'

end

